### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by tanercanbilgin** [FAUSheppy/open-web-leaderboard#2]
can you teach me how can i run it on my ubuntu 18.04 vds server? thanks :)

**Comment by FAUSheppy** [comment]
The READMEs should tell you anything you need to know:

https://github.com/FAUSheppy/open-web-leaderboard

And if you are talking about the full stack:
https://github.com/FAUSheppy/skillbird
https://github.com/FAUSheppy/skillbird-sourcemod

If you are stuck at one point or think the documentation is unclear I am happy to clarify it.

**Comment by tanercanbilgin** [comment]
thank you so much, i have a haxball server and im recording my server stats with database. when i see your project it gave me an idea that our server needs something like that. i have only one database file, i want to show it in website actively. can you help me about it? i want to give a credit to you in our website

**Comment by FAUSheppy** [comment]
If you have your own database (presumably with a different schema), then you could theoretically rewrite the [DatabaseConnection-class](https://github.com/FAUSheppy/open-web-leaderboard/blob/master/database.py). But then again, you are not really asking any specific questions.

I can't help you building your entire website, unless you have a specific question regarding this project, I'll have to close this Issue.

**Comment by tanercanbilgin** [comment]
I wrote website from 0 and connected database, it shows leaderboard like i wanted. I need only one help and it is paging sqlite database in php. Do you know anything about it?

**Comment by tanercanbilgin** [comment]
done, thanks for help
